### ISSUE TITLE
Should also add middle click to paste from Primary Selection on Linux

### ISSUE THREAD

**Issue by Spudd86** [CudaText-addons/cuda_auto_copy#1]
This plugin only solves half the problem of properly supporting the Primary Selection on Linux, it would be nice if the corresponding paste action was also added.

**Comment by Alexey-T** [comment]
For middle-click-paste, plugin is not needed.
Wiki info:
https://wiki.freepascal.org/CudaText#Paste_with_middle-button-click
does it help?

**Comment by Spudd86** [comment]
Yup, thanks
